version: '3.8'

services:
  localhost:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - localhost
    env_file:
      - .env

volumes:
  postgres_data:
